import { StateGraph, StateSchema, type GraphNode, START, END } from "@langchain/langgraph";
import z from "zod";
import { 
  mistralModel, 
  cohereModel, 
  geminiModel, 
  groqModel, 
  deepseekModel, 
  claudeModel, 
  gptModel 
} from "./model.ai.js";
import { createAgent, providerStrategy, HumanMessage } from "langchain";
import config from "../config/config.js";

const state = new StateSchema({
  problem: z.string().default(""),
  model_1: z.string().default("mistral"),
  model_2: z.string().default("cohere"),
  judge_model: z.string().default("gemini"),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_feedback: z.string().default(""),
    solution_2_feedback: z.string().default(""),
    question_score: z.number().default(0),
  }),
});

function getModel(name: string) {
  const modelName = name?.toLowerCase() || "";
  if (modelName.includes("gemini")) {
    return geminiModel;
  } else if (modelName.includes("mistral")) {
    return mistralModel;
  } else if (modelName.includes("cohere")) {
    return cohereModel;
  } else if (modelName.includes("groq")) {
    return groqModel;
  } else if (modelName.includes("deepseek")) {
    return deepseekModel;
  } else if (modelName.includes("claude")) {
    return claudeModel;
  } else if (modelName.includes("gpt") || modelName.includes("github") || modelName.includes("openai")) {
    return gptModel;
  } else {
    return geminiModel;
  }
}

function hasApiKeyForModel(modelName: string): boolean {
  const name = modelName?.toLowerCase() || "";
  if (name.includes("gemini")) return !!config.GOOGLE_API_KEY;
  if (name.includes("mistral")) return !!config.MISTRAL_API_KEY;
  if (name.includes("cohere")) return !!config.COHERE_API_KEY;
  if (name.includes("groq")) return !!config.GROQ_API_KEY;
  if (name.includes("deepseek")) return !!config.OPENROUTER_API_KEY;
  if (name.includes("claude")) return !!config.OPENROUTER_API_KEY;
  if (name.includes("gpt") || name.includes("github") || name.includes("openai")) return !!config.GITHUB_API_KEY;
  return false;
}

const solutionNode: GraphNode<typeof state> = async (state) => {
  const m1 = getModel(state.model_1);
  const m2 = getModel(state.model_2);

  const [res1, res2] = await Promise.all([
    m1.invoke(state.problem),
    m2.invoke(state.problem),
  ]);

  return {
    solution_1: (typeof res1.content === 'string' ? res1.content : '') || "",
    solution_2: (typeof res2.content === 'string' ? res2.content : '') || "",
  };
};

const judgeNode: GraphNode<typeof state> = async (state) => {
  const { problem, solution_1, solution_2, judge_model } = state;
  const jModel = getModel(judge_model);

  const judge = createAgent({
    model: jModel,
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_feedback: z.string(),
        solution_2_feedback: z.string(),
        question_score: z.number().min(0).max(10),
      }),
    ),
    systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models to the following problem:
         ${problem}. Please provide a score out of 10 for each solution, along with your reasoning for the scores. Additionally, evaluate the quality/clarity/complexity of the question/problem itself and score it out of 10.`,
  });

  const judgeResponse = await judge.invoke({
    messages: [
      new HumanMessage(`
            Problem: ${problem},
            Solution 1:${solution_1},
            Solution 2:${solution_2},
            Please evaluate the solutions and the problem quality, providing scores and reasoning.
            `),
    ],
  });

  const {
    solution_1_score,
    solution_2_score,
    solution_1_feedback,
    solution_2_feedback,
    question_score,
  } = judgeResponse.structuredResponse;

  return {
    judge: {
      solution_1_score,
      solution_2_score,
      solution_1_feedback,
      solution_2_feedback,
      question_score,
    },
  };
};

const graph = new StateGraph(state)
  .addNode("solutions", solutionNode)
  .addNode("judgeNode", judgeNode)
  .addEdge(START, "solutions")
  .addEdge("solutions", "judgeNode")
  .addEdge("judgeNode", END)
  .compile();

export default async function runGraph(
  problem: string,
  model_1 = "mistral",
  model_2 = "cohere",
  judge_model = "gemini"
) {
  // Check if API keys are configured. If not, throw an error
  const hasKeys =
    hasApiKeyForModel(model_1) &&
    hasApiKeyForModel(model_2) &&
    hasApiKeyForModel(judge_model);

  if (!hasKeys) {
    throw new Error("Missing required API keys for the chosen models.");
  }

  const result = await graph.invoke({
    problem: problem,
    model_1: model_1,
    model_2: model_2,
    judge_model: judge_model,
  });
  return result;
}