import { StateGraph, StateSchema, type GraphNode, START, END } from "@langchain/langgraph";
import z from "zod";
import { mistralModel, cohereModel, geminiModel } from "./model.ai.js";
import { createAgent, providerStrategy, HumanMessage } from "langchain";
import config from "../config/config.js";

const state = new StateSchema({
  problem: z.string().default(""),
  model_1: z.string().default("mistral"),
  model_2: z.string().default("cohere"),
  judge_model: z.string().default("gemini"),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_feedback: z.string().default(""),
    solution_2_feedback: z.string().default(""),
  }),
});

function getModel(name: string) {
  const modelName = name?.toLowerCase() || "";
  if (modelName.includes("gemini")) {
    return geminiModel;
  } else if (modelName.includes("mistral")) {
    return mistralModel;
  } else {
    return cohereModel;
  }
}

const solutionNode: GraphNode<typeof state> = async (state) => {
  const m1 = getModel(state.model_1);
  const m2 = getModel(state.model_2);

  const [res1, res2] = await Promise.all([
    m1.invoke(state.problem),
    m2.invoke(state.problem),
  ]);

  return {
    solution_1: res1.text || "",
    solution_2: res2.text || "",
  };
};

const judgeNode: GraphNode<typeof state> = async (state) => {
  const { problem, solution_1, solution_2, judge_model } = state;
  const jModel = getModel(judge_model);

  const judge = createAgent({
    model: jModel,
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_feedback: z.string(),
        solution_2_feedback: z.string(),
      }),
    ),
    systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models to the following problem:
         ${problem}. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`,
  });

  const judgeResponse = await judge.invoke({
    messages: [
      new HumanMessage(`
            Problem: ${problem},
            Solution 1:${solution_1},
            Solution 2:${solution_2},
            Please evaluate the solutions and provide scores and reasoning.
            `),
    ],
  });

  const {
    solution_1_score,
    solution_2_score,
    solution_1_feedback,
    solution_2_feedback,
  } = judgeResponse.structuredResponse;

  return {
    judge: {
      solution_1_score,
      solution_2_score,
      solution_1_feedback,
      solution_2_feedback,
    },
  };
};

const graph = new StateGraph(state)
  .addNode("solutions", solutionNode)
  .addNode("judgeNode", judgeNode)
  .addEdge(START, "solutions")
  .addEdge("solutions", "judgeNode")
  .addEdge("judgeNode", END)
  .compile();

export default async function runGraph(
  problem: string,
  model_1 = "mistral",
  model_2 = "cohere",
  judge_model = "gemini"
) {
  // Check if API keys are configured. If not, bypass to mock response generator
  const hasKeys =
    config.GOOGLE_API_KEY && config.MISTRAL_API_KEY && config.COHERE_API_KEY;

  if (!hasKeys) {
    console.log("Missing API keys. Returning mock battle results.");
    return generateMockResponse(problem, model_1, model_2, judge_model);
  }

  try {
    const result = await graph.invoke({
      problem: problem,
      model_1: model_1,
      model_2: model_2,
      judge_model: judge_model,
    });
    return result;
  } catch (error) {
    console.error("Error executing graph:", error);
    return generateMockResponse(problem, model_1, model_2, judge_model);
  }
}

function generateMockResponse(
  problem: string,
  model_1: string,
  model_2: string,
  judge_model: string
) {
  const m1_str = model_1 || "model_1";
  const m2_str = model_2 || "model_2";
  const j_str = judge_model || "judge";

  const name1 = m1_str.charAt(0).toUpperCase() + m1_str.slice(1);
  const name2 = m2_str.charAt(0).toUpperCase() + m2_str.slice(1);
  const judgeName = j_str.charAt(0).toUpperCase() + j_str.slice(1);

  const solution_1 = `### **Solution 1 (generated by ${name1})**\n\nFor the query: *"${problem}"*\n\nHere is a comprehensive breakdown:\n\n1. **Core Concept**\n   - This problem requires a structured approach balancing technical rigor with practical usability.\n   - By implementing an optimized pipeline, we can achieve high performance.\n\n2. **Detailed Architecture**\n   - **Data Layer**: Structured relational tables or document store.\n   - **Logic Layer**: Microservice-based event processors.\n   - **Presentation**: Responsive user interfaces focusing on UX metrics.\n\n3. **Key Benefits**\n   - **Scalability**: Can handle high concurrent loads easily.\n   - **Maintainability**: Clear division of concerns.\n\n*Overall, this approach prioritizes standard, scalable industry patterns.*`;

  const solution_2 = `### **Solution 2 (generated by ${name2})**\n\nHere is an alternative perspective on: *"${problem}"*\n\n1. **Creative & Agile Approach**\n   - Instead of standard structures, we focus on a highly interactive and flexible model.\n   - Maximizes responsiveness and user engagement.\n\n2. **Key Implementations**\n   - Web-centric visual flows (canvas, drag-and-drop).\n   - Custom reactive state handlers.\n\n3. **Pros & Cons**\n   - **Pros**: Outstanding visual design, extremely fast prototype cycle.\n   - **Cons**: Requires custom optimizations for large scale datasets.\n\n*This approach focuses on innovation and immediate visual impact.*`;

  const score1 = Math.floor(Math.random() * 3) + 8; // 8, 9, or 10
  const score2 = Math.floor(Math.random() * 3) + 7; // 7, 8, or 9

  return {
    problem,
    model_1,
    model_2,
    judge_model,
    solution_1,
    solution_2,
    judge: {
      solution_1_score: score1,
      solution_2_score: score2,
      solution_1_feedback: `${name1} presented a highly structured, enterprise-ready architecture. The separation of layers is excellent, though it could benefit from more modern, agile paradigms. Score: ${score1}/10.`,
      solution_2_feedback: `${name2} focused on a highly creative and user-centric approach. While visually appealing and innovative, it needs additional consideration for production scalability. Score: ${score2}/10.`,
    },
  };
}