import { StateGraph, StateSchema, type GraphNode,START,END } from "@langchain/langgraph";
import z from "zod";
import { mistralModel, cohereModel, geminiModel } from "./model.ai.js";
import { createAgent, providerStrategy, toolStrategy,HumanMessage } from "langchain";

const state = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_feedback: z.string().default(""),
    solution_2_feedback: z.string().default(""),
  }),
});

const solutionNode: GraphNode<typeof state> = async (state) => {
  const [mistral_solution, cohere_solution] = await Promise.all([
    mistralModel.invoke(state.problem),
    cohereModel.invoke(state.problem),
  ]);

  return {
    solution_1: mistral_solution.text,
    solution_2: cohere_solution.text,
  };
};

const judgeNode: GraphNode<typeof state> = async (state) => {
  const { problem, solution_1, solution_2 } = state;

  const judge = createAgent({
    model: geminiModel,
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_feedback: z.string(),
        solution_2_feedback: z.string(),
      }),
    ),
    systemPrompt: `You are a judge tasked with evaluating two solutions generated by the different AI models ,to the following problem:
         ${problem}.please provide a score out of 10 for each solution , along with yo
         ur reasoning for the scores.
         `,
  });

   const judgeResponse = await judge.invoke({
    messages:[
        new HumanMessage(`
            Problem: ${problem},
            Solution 1:${solution_1},
            Solution 2:${solution_2},
            Please evaluate the solutions and provide scores and reasoning.
            `)
    ]
   })

   const{
    solution_1_score,
    solution_2_score,
    solution_1_feedback,
    solution_2_feedback,
   } = judgeResponse.structuredResponse


   return {
    judge:{
        solution_1_score,
        solution_2_score,
        solution_1_feedback,
        solution_2_feedback
    }
   }
};


const graph = new StateGraph(state)
.addNode("solutions",solutionNode)
.addNode("judgeNode",judgeNode)
.addEdge(START,"solutions")
.addEdge("solutions","judgeNode")
.addEdge("judgeNode",END)
.compile()



export default async function (problem:string){
    const result = await graph.invoke({
        problem:problem
    
    })

    return result;
}